https: false
certpath:
certkey:
host: 0.0.0.0
port: 8085
recordpath: ./hls
db:
  adapter: mysql # mysql postgres sqlite3
  host: localhost
  port: 3306
  name: musicplayer
  user: root
  password: 12345678
