https: false
certpath:
certkey:
host: 0.0.0.0
port: 8085
recordpath: ./hls
db:
  adapter: sqlite3 # mysql postgres sqlite3
  host: mysql
  port: 3306
  name: goirisadminapi
  user: root
  password: 123456
